# Use custom format
format = '''
[](bold green)$os$directory$jobs$git_branch$git_state$git_status$character'''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = '[ï‘ ](bold green) '
error_symbol = '[ó°‘™](bold red) '

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = 'î‚  '
truncation_length = 25
truncation_symbol = '..'


[git_status]
style = 'yellow'
conflicted = 'ó°—– '
ahead = 'ó°¬­ ${count}'
diverged = 'ó°¬­ ${ahead_count}ó°¬§ ${behind_count}'
behind = 'ó°¬§ ${count}'
up_to_date = 'ó°—¡ '
untracked = 'î¬² '
stashed = 'ó±‡® '
modified = 'ó°¶ '
staged = 'ó±¤§ '
renamed = 'ó°·¹ '
deleted = 'ó°…š '

[jobs]
symbol = 'î© '

[os]
disabled = false

[os.symbols]
Alpine = "ïŒ€ "
Android = "ğŸ¤– "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
Fedora = "ğŸ© "
FreeBSD = "ğŸ˜ˆ "
Gentoo = "ğŸ—œï¸ "
Linux = "ï…¼ "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
OpenBSD = "ğŸ¡ "
openSUSE = "ğŸ¦ "
Redhat = "ğŸ© "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "î¬² "
Windows = "ó°–³ "

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = '%T'
utc_time_offset = '+8'
